### ISSUE TITLE
auto height with zoom transition

### ISSUE THREAD

**Issue by zassq** [euvl/vue-js-modal#177]
There's a weird behaviour for auto height with zoom transition, not sure you guys have noticed or not.

The scenario is:
- zoom transition
- auto height on modal
- page height is larger than window
- happens even set a delay value (tried from 20 - 2000)
- vue-js-modal version is 1.3.10

The modal box starts with a vertical position at 50% of page instead of window, even I set a delay to have overlay comes in earier. Sorry can't replicate it in tools like jsfiddle, I can just share some screemshots, hope they can help.

After the transition, the modal box would jump to the correct position, which is in the middle of the window.

It's fine with other transition (however, I only tried with 'fade')

![image](https://user-images.githubusercontent.com/1635161/36364939-489eaaec-159b-11e8-9e84-82fd3681e2a6.png)
![image](https://user-images.githubusercontent.com/1635161/36365008-9a74f2ea-159b-11e8-95c7-8c1119c01ec5.png)
![image](https://user-images.githubusercontent.com/1635161/36365073-e5933cbe-159b-11e8-8493-22e8a44a35a1.png)

**Comment by wmcmurray** [comment]
@euvl So why does this issue has been closed exactly ? I'm having similar issues while trying to implement a zoom transition with height auto. My modal gets wrongly positioned before the transition starts and remain that way until the transition finishes, where a JS re-positioning apparently occurs and fix positioning.

If I resize the window during the transition, it triggers that JS positioning tho, but it does not solve my problem because user would have to resize the browser constantly during transition lol

Not sure how CSS transitions and Javascript-based positioning could go well together, seems a bit old-school to me... why not use flexbox to position modal inside of his parent overlay ? :thinking:

**Comment by euvl** [comment]
> @euvl So why does this issue has been closed exactly ? 

Because no-one found a solution to this issue, there was no further discussion or any other actions. 

It is not an agency to fix problems in your projects.

I don't get paid and what get back for sharing my code is random people writing "so why this issue has been closed exactly", as if they are my project managers or employers.

**Comment by wmcmurray** [comment]
Then why did you publish open source code in the first place if you don't want to help ? :thinking: I'm not asking you to fix my project, but I'm expecting you to transmit your knowledge about your own code (that's why I asked the question).

If you had thought this issue through and ended up with a conclusion, why not just write it down so other people can start from there and make a pull request if it's fixable ?

**Comment by wmcmurray** [comment]
Also @zassq , I just experimented with flexbox and here is what I did to make sure the modal is centered during my zoom transition : 

```
.v--modal-overlay {
  display: flex;
  align-items: center;
  justify-content: center;
}
.v--modal-box {
  position: static !important;
}
```
It basically overwrites javascript positioning to let flexbox do it's magic. But keep it mind that this may conflicts with other settings like `pivotX` or `pivotY` ...but it works for my case.
