### ISSUE TITLE
Toggle function for dynamic modals

### ISSUE THREAD

**Issue by JFonsecaSpot** [euvl/vue-js-modal#206]
Accept both prop/params. Ignore prop to close, otherwise open with .show()

In the mean time, is there a way to check if a dynamic modal is opened just before .show()

Good job on vue-js-modal

**Comment by euvl** [comment]
Sorry, i didn't understand what you wrote 🤔

**Comment by JFonsecaSpot** [comment]
Sorry I was not clear enough. Maybe its to specific for my situation.

Launching a modal assumes it is going to fit the whole screen so the 'close' action can be contained in the modal component itself. However, you can have events or modal configurations that requires to close the modal from outside. 

What I was proposing is a $modal.toggle() which would accept the same $modal.show() inputs. It first checks if the dynamic component is visible on screen before executing $modal.show() or $modal.hide() accordingly.

I am new with Vue otherwise I would try to implement it myself.

Regards

**Comment by euvl** [comment]
It actually has toggle

https://github.com/euvl/vue-js-modal/blob/master/src/index.js#L42

**Comment by JFonsecaSpot** [comment]
Does it work for dynamic modals?

How would set up the modal configuration? $modal.toggle only accepts the component and params.

**Comment by euvl** [comment]
oh right, my bad. no, it does not work for dynamic modals 😃

**Comment by JFonsecaSpot** [comment]
Is there a non hacky way to check if the dynamic modal is active?
Because you just fork to show/hide after the check, I would say.

**Comment by euvl** [comment]
no, i don't think there is. You can give it a go if you have spare time 👍

**Comment by JFonsecaSpot** [comment]
I will. Thank you

**Comment by euvl** [comment]
To be honest, conceptually, toggle function for a thing with life-cycle `create => show => destroy` doesn't make much sense. You do not toggle it as every time , you create it, because you pass a render function & props, meaning  that your modal does not have persistent state. 

I would be very careful with designing such a functionality as it seems can lead to bugs and misunderstanding.

If you will create PR i will be happy to discuss it though 👍
