### ISSUE TITLE
How can I call $modal.show in my js module? 

### ISSUE THREAD

**Issue by wwwjun** [euvl/vue-js-modal#237]
#### Question: 

How can I call $modal.show in my js module? 

#### Screenshots:

![image](https://user-images.githubusercontent.com/11974533/40782149-0ac01560-6511-11e8-9146-04c634e5a2cc.png)

Please help me, Thanks.

**Comment by euvl** [comment]
You cannot. 

Mixing feature of your particular view and util function is wrong and vue.js will not let you do that.

**Comment by wwwjun369** [comment]
@euvl  Sorry, I'm new to the vue framework. The standard way is how to do? Please help me, thanks.

**Comment by wwwjun** [comment]
@euvl Sorry, I'm new to the vue framework. The standard way is how to do? If you are free, please help me, thanks. Maybe I should go back to study, thanks.

**Comment by euvl** [comment]
I assume you make your api call from some component (for example Page component). It seems to be  a bad practice to handle your visual feedback inside api call. Rather than that you can return a promise (or callback) from your api call and show notification in your Page component.

This way you will have all your visual stuff happening in one place (file/module/whatever) and all your network stuff in another.

**Comment by wwwjun** [comment]
@euvl Thanks, you are right, but I just want to intercept it right here and I don't want to handle it in every component, Maybe I should use vuex to commit state or  configure routing for the modal.
