### ISSUE TITLE
"Closed" event doesn't emit in IE

### ISSUE THREAD

**Issue by souljorje** [euvl/vue-js-modal#309]
### Problem: 

I have a decorator component around vModal for some default styles and behaviour. Can't understand why only in IE "closed" event doesn't emit after close. "Before-open" and "before-close" events are working well.

#### Example on codesandbox:
>Codesandbox doesn't work in IE unfortunately.    
https://codesandbox.io/s/138o0rqn8j

**Comment by VictorCazanave** [comment]
@souljorje I also use a decorator component around vue-js-modal and I don't have this problem on IE 11. I tried your codesandbox and the `closed()` method is still called.
Which version of IE do you use?
Maybe you can try with the last version of vue-js-modal (1.3.26).

**Comment by euvl** [comment]
Strange i would expect it either to work or not to work, rather then emit events sometimes :strange:

**Comment by souljorje** [comment]
@euvl Really strange. I tried to dive to source code, but still cant understand what a hell. I use IE 11.

**Comment by VictorCazanave** [comment]
@souljorje I didn't run codesandbox on IE, I just copy/paste your AppModal component in my local project 😄 
You can try on codepen. It's less convenient because you need to copy/paste the code of vue-js-modal (like I did with [vue-js-toggle](https://codepen.io/VictorCazanave/pen/yxgKKZ)) but I think you can test it on IE in [full page mode](https://codepen.io/VictorCazanave/full/yxgKKZ/).
