### ISSUE TITLE
iphone 8p can't catch event

### ISSUE THREAD

**Issue by max-level** [euvl/vue-js-modal#313]
#### Problem: 

iphone 8p can't catch event.

ex: @opened @closed 

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by coxy121** [comment]
I have also experienced this issue. It was introduced in version 1.3.21

There is also an issue with the modal not centering to the screen, and it is instead positioning the modal top at the center of the screen on an iPhone.

**Comment by euvl** [comment]
I can't see how I can test it without an actual device... feel free to fix it 😄

**Comment by coxy121** [comment]
@euvl I am happy to help to try and fix as I have a device to test on. Do you have any ideas what might be causing the issue with the event? I have debugged and the last version it worked at was 1.3.20.

Going through the examples, it seems that when height is set to auto on an iPhone instead of positioning to the modal top at the center of the screen on an iPhone.

**Comment by euvl** [comment]
This is so so weird!
