### ISSUE TITLE
Close Button Example

### ISSUE THREAD

**Issue by zherman91** [euvl/vue-js-modal#316]
#### Problem: 
Cannot seem to get the Close Button slot to work properly. My particular use case involves creating a dynamic modal and passing a component in like this:

```
createModal() {
        this.$modal.show(Network, {
          tenants: this.hierTenants
        }, {
          draggable: false,
          resizable: true,
          // adaptive: true,
          height: 800,
          width: 1200
        });
      }
```

#### Example & screenshots:
Here is how i have the slot declared: 

```
<modals-container v-on:handleTreeNodeClick="handleTreeNodeClick($event)">
      <div slot="top-right">
        <button @click="$modal.hide('mynetwork')">❌</button>
      </div>
    </modals-container>
```

So my question is, can you provide an example of how to implement the top-right close button? I really appreciate the help. 

Thanks. 
...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by cicsolutions** [comment]
I've not tested the vue-js-modal component a ton when using it dynamically, but you may want to try setting the name prop to be 'mynetwork'.

```
createModal() {
        this.$modal.show(Network, {
          tenants: this.hierTenants
        }, {
          name: 'mynetwork', // notice here how we are setting the name prop of the modal
          draggable: false,
          resizable: true,
          // adaptive: true,
          height: 800,
          width: 1200
        });
      }
```

Then, I believe your slotted closed button will work as you have it coded because it references the same modal name:
`<button @click="$modal.hide('mynetwork')">❌</button>`

**Comment by zherman91** [comment]
Awesome! Thanks for getting back to me! I really appreciate that. I will give it a try and report back. Thanks again!

Zac

**Comment by cicsolutions** [comment]
Also, I think because you are instantiating the modal dynamically, you could also code your close button like this:

`<button @click="$emit('close')">❌</button>`

Again, I'm not super-familiar with using the component dynamically, so I'm not sure your setup for the <modals-container> and the top-right slot are set up properly.  If they are working for you, then run with it!

**Comment by zherman91** [comment]
Sounds like a plan! Thanks again!
