### ISSUE TITLE
Allow `vh` and `vw` units for width & height

### ISSUE THREAD

**Issue by drewrawitz** [euvl/vue-js-modal#327]
#### Problem: 
I'd love to be be able to use the following:

```
<modal name="userLogin" :scrollable="true" width="100vw" height="100vh"></modal>
```

for a full-screen modal that I need to replicate in my design.

#### Example & screenshots:
I get the following error:
![](https://monosnap.com/image/yIEW4tmoIBRfR2CQ2cOfdWibwcZDcD.png)

Is there any reason not to allow those units?

Thanks!

**Comment by euvl** [comment]
if you will implement it - go for it. Those are not css values. width/height are recalculated if your modal draggable or resizable, or your screen size changes.

**Comment by nathanboktae** [comment]
> Those are not css values.

Those are totally legit values. I use `vh` and `vw` for my modals too, and since CSS is for styling and not code, I use `!important` to override what `vue-js-modal` is doing, like so:

![image](https://user-images.githubusercontent.com/1989335/46836834-f1fcc400-cd67-11e8-861b-4b8d18468339.png)

Perfectly centered, dynamic modals via flexbox 🎉. There's no reason to force users to specify exact pixel widths and heights for a modal in this day and age.

**Comment by euvl** [comment]
Could you be more passive agressive pls @nathanboktae ?
