### ISSUE TITLE
Close all open modals? Any way to do it or a missing feature?

### ISSUE THREAD

**Issue by burzum** [euvl/vue-js-modal#350]
There is a case when I want to open a new modal but close all others that are open.

So instead of providing the name of each modal in every spot where a close can be triggered, I would prefer if I could simply do a "close all" somehow. Any suggestions how to get this done?

**Comment by adamreisnz** [comment]
I'd also like to know. We need to close all/any modals that are open for example when the user is logged out.

**Comment by euvl** [comment]
Hey guys, i've noticed some thumb ups, feel free to try & implement it, noone stops you guys 😄 👍

**Comment by burzum** [comment]
@euvl any recommendation on how to tackle this problem?

I can't find a list of modals are something. Guess I would have somehow to fire a global event that goes by a selector and closes them all somehow? I don't mind implementing it but it's not that easy for me.

**Comment by adamreisnz** [comment]
@burzum looks like there's an array of modals that is stored in the ModalContainer class:

https://github.com/euvl/vue-js-modal/blob/master/src/ModalsContainer.vue#L38

Simplest solution appears adding a `removeAll` method to the modals container, with similar code to the one in [remove](https://github.com/euvl/vue-js-modal/blob/master/src/ModalsContainer.vue#L50-L57), looping all of the modals and closing/removing them all.

In fact the remove code could also be optimised by using a map rather than an array, based on ID, so that the modals don't have to be looped each time to close it. Then again, there are unlikely to be many modals that are open at any given time so that's not that big of a deal.

**Comment by trandaison** [comment]
If you are using __Dynamic Modals__, you can bind a `key` to the `modal-container`, when you want to close all modals, just change the value of `key`. 

In my case, I want to close all modals on the route changes, then I'm doing something like this.
```html
<modals-container :key="$route.fullPath"/>

**Comment by Kylexii** [comment]
@trandaison good idea! useful in SPA when route changes, kind of tricky though

**Comment by JackEdwardLyons** [comment]
Any news on the `closeAll` option?

**Comment by euvl** [comment]
Added `hideAll` for dynamic modals

**Comment by nezaboravi** [comment]
am getting hideAll is not a function

**Comment by Grinnbob** [comment]
Solution

<template>
      <modals-container ref="modal_name"/>
</template>

this.$refs["modal_name"].modals = []
