### ISSUE TITLE
Developer setup terribly outdated

### ISSUE THREAD

**Issue by Fusseldieb** [euvl/vue-js-modal#360]
I've been trying to replicate the developer setup, running `npm install` and all necessary stuff to fix some stuff and make a pull request. 

What I've found is that a lot of packages are outdated and contain (severe) **security** and **performance** issues. Trying to upgrade them breaks everything.

I was trying for almost 3 hours to fix those issues, but got stuck and finally gave up.

@euvl Help us out there. Would be nice if you do some "housekeeping" sometimes...

Thank you.

**Comment by euvl** [comment]
> Developer setup terribly outdated

> Would be nice if you do some "housekeeping" sometimes...

I've stopped doing "housekeeping" mostly because of posts like this. People demanding stuff to be done. With all the respect but I have my own life and you are using my code for free, without any extra terms. It saves either a bit of time/money to you or your company.. and what you do, you say "@euvl do more because it is not enough. I've spent 3 HOURS (!!!) while you were supporting this project for 2+ years and i'm not happy.".

Thanks. Waiting for your PR.

**Comment by euvl** [comment]
Great, thanks for your help 👍 

I didn't mean to be rude, hopefully, you can understand me. 

Also as you mentioned project abandoning, one of the main reasons why people abandon their projects, is pretty much, because of the pressure from users to deliver features and "fix their projects". 

In my case, I get ± 10 messages a day saying that I either MUST to add a feature "X" or MUST fix "Y" because it is "wrong" and "does not work in my project", etc. It is super frustrating and seeing smth like"developer setup terrible" is not exactly what i had in mind when started sharing my mini projects 😄

**Comment by Fusseldieb** [comment]
@euvl I just got it working through Vue-CLI 3, can/should I still continue (would be nice) or do you necessarily _want_ to use Webpack as standalone?
![image](https://user-images.githubusercontent.com/4715129/48478947-e7ad6a00-e7ec-11e8-9f71-7e0590a8c35c.png)

![image](https://user-images.githubusercontent.com/4715129/48479018-26dbbb00-e7ed-11e8-9362-eec43f7a67e3.png)

**Comment by euvl** [comment]
If you are referring to the demo website - if it works with vue cli, feel free to use it 👍 I remember when i was writing the webpack config for it, there was no way to refer to the library in a parent/sibling folder in an easy way. The current config will refresh the website in case the plugin /dist is updated (hence, testing is easier). If you can achieve the same result with the newer tool - its awesome, feel free to make a PR 👍

**Comment by OmgImAlexis** [comment]
Still an issue.
