### ISSUE TITLE
All modals content is being ran even when hidden

### ISSUE THREAD

**Issue by dmotors** [euvl/vue-js-modal#375]
#### Problem: 

Let's just say when all modals are closed it is still running the contents within the modal. I was under the impression that the content of the modal is only ran upon calling it to show not when it's hidden.

#### Example & screenshots:

```
<modal name="show-test" width="430px" height="438px">
	<div class="container">
		{{ testConsole() }}
	</div>
</modal>

testConsole() {
	console.log('contents has been ran');
}
```

https://i.imgur.com/M5MkAHK.png

As you can see above screenshot, no modals are open yet my modal still processed what was inside of it. This becomes problematic when I have a lot of conditions or syntax that was meant to be ran once modal is shown.

**Comment by dmotors** [comment]
Temporary workaround I'm doing is:

```
<modal name="show-test" @opened="modals.showtest = 1" @closed="modals.showtest = 0">
	<div v-if="modals.showtest">
		{{ testConsole() }}
	</div>
</modal>
```

Not sure if this is an efficient or ideal way but it did solve my problem. Feels redundant to do this unless it is just how JS works that anything I put under <template> would be all run on page load regardless if the modal is hidden or not.

**Comment by euvl** [comment]
If your modal is mounted, then it definitely should run the content within your modal. This is done to make sure that you will not block or slow down your website when you show the modal and animation works smoothly. It is fairly easy to use beforeOpen, opened hooks instead of beforeMount and mounted. Check out readme and examples, they might be useful.

Thanks, 👍
