### ISSUE TITLE
blur effect on background

### ISSUE THREAD

**Issue by albl2008** [euvl/vue-js-modal#376]
#### I need HELP: 
Hello, im new in issues, and helpwanted! I want to apply a blur effect in the page when a modal is oppened...how can i do that?

Sorry for my bad english, im from Argentina!
...

**Comment by euvl** [comment]
Hey, if you put your modal OUTSIDE of your content block, for example
```
Root
 |- modals 
 |   |- MyModal
 |
 |- content
```

You can set the style of your app's content to `filter: blur(5px)` for example, this way modal still will be visible and unblurred but the content will be blurred.

Otherwise, i don't think you will be able to blur background with this plugin 😢

**Comment by shaniqwa** [comment]
would be useful if there was a way to know if a modal is open, like `this.$modal.isOpen()` , then it will be easy to toggle a blur class on the app root container
