### ISSUE TITLE
I cannot control the width and height of the modal through css classes 

### ISSUE THREAD

**Issue by UthpalaHeenatigala** [euvl/vue-js-modal#437]
#### Problem: 
The classes I supply to the classes prop gets overridden by the styles added internally. 

Trying to style the modal using tailwind classes :)

**Comment by euvl** [comment]
Hey, this plugin would not act upon classes. It was designed to be programmatically adaptable.

**Comment by angujo** [comment]
Am not looking into opening the issue, but proposing a solution.
Have implemented the solution below to allow usage of bootstrap's grid classes on the width parameter.
It works for me but not fluid, since you need to close and open the modal to recalculate;

```
function classDimension(cls) {
                let wd = window.innerWidth,
                    clss = cls.split(' ').map(c => {
                        let nm = parseFloat(c.toString().trim().replace(/^(col-(xl|md|sm|lg)-)/gi, ''));
                        nm = isNaN(nm) ? 12 : nm;
                        if (c.toString().trim().startsWith('col-xl-')) return {dv: nm, mw: 1200};
                        if (c.toString().trim().startsWith('col-lg-')) return {dv: nm, mw: 960};
                        if (c.toString().trim().startsWith('col-md-')) return {dv: nm, mw: 720};
                        if (c.toString().trim().startsWith('col-sm-')) return {dv: nm, mw: 540};
                    });
                clss = _.sortBy(clss, (f) => f.mw);
                clss.reverse();
                for (let i = 0; i < clss.length; i++) {
                    if (wd >= clss[i].mw) {
                        cls = [((clss[i].dv / 12) * 100), '%'].join('');
                        break;
                    }
                }
                return cls;
            }
```

You can then use it on the modal parameters;

` this.$modal.show(ModalTemplate, {params:{}}, { name: 'myModal', scrollable: true, clickToClose: false, height: 'auto', width: this.classDimension('col-lg-6 col-sm-12 col-md-8') });
`

**Comment by embluk** [comment]
> Hey, this plugin would not act upon classes. It was designed to be programmatically adaptable (for example, be draggable, resizable, etc).

What about CSS media queries?
