### ISSUE TITLE
How to reuse a modal as a normal component

### ISSUE THREAD

**Issue by ricky11** [euvl/vue-js-modal#539]
#### Problem: 

I have a modal window, that i would like to reuse as a normal component, by importing it in to another parent component, but instead of display it as a modal i would want it to be displayed as a normal child component.  So instead of overlay with z-index, i would like the z-index to be 0.
...

#### Example & screenshots:

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by seanzi86** [comment]
Hello Ricky,
This looks like you want to move the contents of the modal into a new SFC and then use this component both in a modal and in a view?

If this is the case, i tend to create new component and use dynamic modals using the `this.$modal.show(ComponentName);` method. You can read more about it [here](https://github.com/euvl/vue-js-modal#dynamic-modals).

**Comment by ricky11** [comment]
Yes.  But the new component will it show the modal with a z-index? will the overlay still be accessible?

**Comment by ricky11** [comment]
Sorry if im not so clear, as i want to use my modal as a simple component as well where the component can also be inserted in to pages (not as a modal) but just a normal component (without any z-index or background overlay)

**Comment by seanzi86** [comment]
Hello @ricky11,
I have created a sandbox [here ](https://codesandbox.io/s/naughty-poincare-knlqs)which demonstrates what I think you are looking for. It can display the MyComponent in both the page and in a modal in that page.
Please can you take a look and see if this is what you're looking for?

**Comment by ricky11** [comment]
Oh.. so i dont need to wrap it in a <modal> tag.  Let me try it , thanks.

**Comment by ricky11** [comment]
Thank you!

The problem i am having (well not sure if its ) is that i want to make the modal with a z-index of 0 (flat with the background) and still have access to the other text/components on the page.  I could do this without injecting the modal, and using a normal component, but i like the built in draggable option.

**Comment by ricky11** [comment]
What does inserting  <modals-container/> in the component do? does it matter where i insert it?
is it to handle clicks outside the modal? Can i use injectModalsContainer: true , any impact here?

**Comment by euvl** [comment]
What does inserting in the component do? 
-just mounts a component, nothing special

does it matter where i insert it?
- not really, just make sure that the modal is not hidden under some conditional rendering. Otherwise you can try to show the modal that does not exist :D (just use common sense there and check docs and demo) 

is it to handle clicks outside the modal?
- not sure what this means, you can handle clicks within the modal

Can i use injectModalsContainer: true , any impact here?
- no impact, if will inject it in the body

Last question : using the event listener 'before-close' how do i run a function in the component?
using a modal i would simply do
<modal @before-open="beforeOpen($event.params.item)"
But now since i am using a dynamic modal, i cant see to let the modal know which function to run when it opens and pass in the params.
- this you will have to figure out yourself unfortunately, you can pass it in params or make that function global, depends 100% on your project really :)
