### ISSUE TITLE
Should modal keep v--modal class when "classes" property is set?

### ISSUE THREAD

**Issue by UgurBasural** [euvl/vue-js-modal#540]
#### Problem: 
Whenever I try to append a class to a modal, it is being seen like it has been applied but instead, v--modal class gets deleted and class styles are not being added.
...

#### Example & screenshots:
         <modal
          name="play-pause"
          :width=100
          :height=100
          :pivotX=0.4
          :pivotY=0.1
          classes="playPause"
        >hello, world!</modal>
<style scoped>
  .playPause {
    position: absolute;
    background-color: rgba(0, 0, 0, 0.5);
    box-shadow: 0 20px 60px -2px rgba(27, 33, 58, 0.4);
    /*text-align: center;*/
   }
</style>

<img width="507" alt="Screenshot 2020-03-13 at 10 45 56" src="https://user-images.githubusercontent.com/26435106/76600752-94e6de00-6518-11ea-8ac5-75d0ab1a14b3.png">

...

I have checked stackoverflow for solutions and 100% sure that issue not in my code.

**Comment by mattkaye** [comment]
@UgurBasural I was stuck with a similar issue. Since the v--modal class is removed completely, you have to add back what you want that was defined in v--modal to your new class(s). I think appending the new class AS WELL as keeping v--modal would have been a nice design choice but it is what it is.

So using SCSS I did something like this and it worked:

```
<modal name="ContactModal" :classes="['modal_margin']">
```

```
.modal_margin {
  margin: 0 auto;
  max-width: 90%;
  background: white;

  @screen lg {
    margin: auto;
    max-width: 100%;
  }
}
```
My goal was to add a bit of margin to the modal on mobile so it wasn't edge to edge.

<img width="554" alt="Screen Shot 2020-04-06 at 9 39 33 AM" src="https://user-images.githubusercontent.com/2780089/78564519-8bd0f000-77ea-11ea-82d1-318989dbb038.png">


Hope this helps.

**Comment by euvl** [comment]
I am wondering if i should keep v--modal class? I've built like that under the assumption that people will want to completely change the styles rather than overwrite those. 

But this is not the first issue where people get confused by it. What do you think guys?

**Comment by mattkaye** [comment]
I would personally keep it and have the user override your class definitions. If you do decide to remove the class, I think you’re just going to have to document it more clearly so it’s less confusing for end users. Just my two cents.

**Comment by euvl** [comment]
Cool, removed in v2
