### ISSUE TITLE
Special usage with Gridsome missing in documentation

### ISSUE THREAD

**Issue by lansolo99** [euvl/vue-js-modal#544]
#### Problem: 
Used with Gridsome, the build will fail with an "ReferenceError: window is not defined" message.
...

I try a lot of workarounds before I realize I should have used a special Gridsome plugin to be able to build properly: https://gridsome.org/plugins/gridsome-plugin-modal

I think it should be stated in the documentation, so that we could save a lot of time :)

**Comment by sagrawal-idrc** [comment]
> I try a lot of workarounds before I realize I should have used a special Gridsome plugin to be able to build properly: https://gridsome.org/plugins/gridsome-plugin-modal

Yes, or the modal should be added to `Vue` object in client context.

**Comment by euvl** [comment]
Hey guys, is Gridsome a big thing? Never seen it before, but if there's something i can do to reduce the pain of integrating with it - let me know 😄 👍

**Comment by lansolo99** [comment]
@euvl  To me, sure it is! It's the equivalent of Gatsby for Vue to generate static sites. Nuxt can do it but Gridsome is entirely focused on this task so I find it's a better fit for this use-case. Glad you can help if you can ! 👍

**Comment by sagrawal-idrc** [comment]
> but if there's something i can do to reduce the pain of integrating with it - let me know 

Thanks, but IMHO, no change should be done / is required in `vue-js-modal` for this. There is already a plugin for this, which can be included in the organisation, I suppose.

Even without using the plugin, the integration is not that difficult.

> ReferenceError: window is not defined

This error, as I wrote before might be arising because the integration is being tried in the non-client context? I think, in `main.js`, inside the default function, `VModal` can be initialised as such (writing from memory, so the syntax might be bit wrong):

```JavaScript
export default function (Vue, { head, isClient }) {
  if (isClient) {
    const VModal = require('vue-js-modal')
    Vue.use(VModal, options)
  }
}
```

**Comment by lesaff** [comment]
This is how I got it to work:

in the `main.js`

```
import VModal from 'vue-js-modal'

export default function (Vue, { router, head, isClient }) {
  if (isClient) {
    Vue.prototype.$modal = VModal
  }
}

**Comment by euvl** [comment]
Nice, i've added FAQ tag, will close this issues as far as everyone is happy
