### ISSUE TITLE
How to apend modal in body?

### ISSUE THREAD

**Issue by Venegrad** [euvl/vue-js-modal#639]
If modal importing in component, it opened in parent relative. How to transfer modal to body close?

![image](https://user-images.githubusercontent.com/9676703/98551230-c087b700-22a5-11eb-9b35-eaa10811b1e6.png)

**Comment by piscis** [comment]
I had the same issue recently and was able to solve it by combine Vue Js Modal with portal vue lib. (https://github.com/LinusBorg/portal-vue)

**Comment by randy-allen** [comment]
For anyone who ran into this issue (like me), the portal-vue solution didn't work for me.  At first it seemed to but I noticed after clicking around the app a bit it would randomly just stop working.  Luckily I was able to fix this directly in this library by using Dynamic modals instead.  This fixes the issue because using Dynamic modals requires you to add a modals-container component into your app, which you can place anywhere, like right in the body tag.

A couple changes in your app to use Dynamic modals:

```
Vue.use(VModal, {
  dynamic: true
});
```

```
<div id="app" class="h-full">
   <modals-container></modals-container>
   ....
</div>
```

Follow the rest of the documentation here on how to call ```this.$modal.open``` to create a dynamic modal that will then be inserted where ever you've placed the modals-container component.

https://euvl.github.io/vue-js-modal/Intro.html#dynamic-modals
