### ISSUE TITLE
Dialog not showing? Vuetify?

### ISSUE THREAD

**Issue by avpavp** [euvl/vue-js-modal#664]
#### Problem: 

Dialog not showing

#### Version:

2.0.0rc6

#### Example & screenshots:

I'm also using Vuetify, and things were working fine, but now the dialog just won't show. I call:

this.$modal.show("dialog", { ...

have:

<v-dialog />

in my template.

but nothing happens. No errors in console; just no dialog shows...

Any ideas?

> I have checked stackoverflow for solutions and 100% sure that this issue is not not related to my code.

**Comment by traed** [comment]
I have the same issue, but not using Vuetify.

**Comment by traed** [comment]
Found the issue for me. The `v-dialog` component wasn't loaded for the particular page I was on.

**Comment by ajuvonen** [comment]
We experienced a similar problem when we first incorporated Vuetify to a project using vue-js-modal. The closed issues seem to suggest that this relates to both Vuetify and vue-js-modal trying to register a v-dialog component. Since we only want a very limited subset of Vuetify components, a working solution for us appears to be to remove vuetify-loader from our project and instead manually import each Vuetify component we want to use when adding the plugin. Of course this means that you can't simultaneously  use v-dialog from Vuetify and vue-js-modal.

Another concept I was thinking was that we could write a custom component import matcher to VuefifyLoaderPlugin that would resolve to vue-js-modals v-dialog component. However, since the guide to doing this at https://vuetifyjs.com/en/features/treeshaking/#custom-dynamic-imports is not very thorough, we opted to go with the first solution. Hope this helps someone else.
